Driver for SAT-Comp
aws-samples/aws-batch-comp-infrastructure-sample pull request #18
Opened 2022-05-25 19:44 UTC by mww-aws

*Issue #, if available:*

*Description of changes:*
This pull request adds a driver for SAT-Comp that will run all files in a given S3 bucket against the distributed solver.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-05-25 20:46 UTC, eidelmanjonathan requested changes

2022-05-25 20:46 UTC, eidelmanjonathan commented on src/arg_satcomp_solver_base/satcomp_solver_driver.py
> +    if os.path.exists(args.json_file) and not args.clean_first:
What's the reason for the cache? Are we expecting to run this script multiple times and have it not finish?

2022-05-25 20:46 UTC, eidelmanjonathan commented on src/arg_satcomp_solver_base/satcomp_solver_driver.py
> +def list_object_keys(s3_resource, problem_bucket: str):
Can we abstract away this S3 stuff into a S3ProblemStore class?

2022-05-25 20:46 UTC, eidelmanjonathan commented on src/arg_satcomp_solver_base/satcomp_solver_driver.py
> +def run_problems(problem_queue, result_queue, input_files, args):
Can we make this more object oriented and have a ProblemRunner so that we don't have to pass around the queues (and that way if things change it will be easier)

This also makes it easier to unit test

2022-05-26 22:25 UTC, mww-aws commented on src/arg_satcomp_solver_base/satcomp_solver_driver.py
> +        result_json = run_one_problem(problem_queue, result_queue, args, s3_uri)
Yes, this is by design.  The script is designed to fail because it indicates that the leader crashed, which is a non-recoverable failure.  If the leader times out, then it will still communicate with us, but this case indicates that no communication has occurred, so we want to check the cluster, make sure that everything is o.k. and restart from the current job.  It is the reason we have a cache (below)

2022-05-26 22:26 UTC, mww-aws commented on src/arg_satcomp_solver_base/satcomp_solver_driver.py
> +    logger = logging.getLogger("log")
Sure, will update.

2022-05-26 22:26 UTC, mww-aws commented on src/arg_satcomp_solver_base/satcomp_solver_driver.py
> +    if os.path.exists(args.json_file) and not args.clean_first:
Yes, in some cases.  It is tied to the issue above where the solver is unresponsive.

2022-05-26 22:27 UTC, mww-aws commented on src/arg_satcomp_solver_base/satcomp_solver_driver.py
> +def list_object_keys(s3_resource, problem_bucket: str):
Sure, will do.

2022-05-26 22:28 UTC, mww-aws commented on src/arg_satcomp_solver_base/satcomp_solver_driver.py
> +def run_problems(problem_queue, result_queue, input_files, args):
Yes.

2022-05-27 04:17 UTC, mww-aws commented on src/arg_satcomp_solver_base/satcomp_solver_driver.py
> +    if os.path.exists(args.json_file) and not args.clean_first:
Done.

2022-05-27 04:17 UTC, mww-aws commented on src/arg_satcomp_solver_base/satcomp_solver_driver.py
> +    logger = logging.getLogger("log")
Done.

2022-05-27 04:17 UTC, mww-aws commented on src/arg_satcomp_solver_base/satcomp_solver_driver.py
> +def run_problems(problem_queue, result_queue, input_files, args):
Done.

2022-05-27 04:17 UTC, mww-aws commented on src/arg_satcomp_solver_base/satcomp_solver_driver.py
> +def list_object_keys(s3_resource, problem_bucket: str):
Done.

2022-05-27 13:18 UTC, eidelmanjonathan requested changes

2022-05-27 13:18 UTC, eidelmanjonathan commented on src/arg_satcomp_solver_base/satcomp_solver_driver.py
> +    def list_object_keys(self, problem_bucket: str):
Can we make the S3ProblemStore have the bucket name as a class attribute so we don't have to pass it here?

And since this is a dedicated object for storing SAT problems can call this something like "list_formulas()"?

2022-05-27 13:18 UTC, eidelmanjonathan commented on src/arg_satcomp_solver_base/satcomp_solver_driver.py
> +            s3_uri = 's3://' + self.s3_bucket + "/" + input_file
I think we should abstract this away and do it in the S3ProblemStore. This will make things easier if we ever want to change the way we send over the problems

2022-05-27 16:41 UTC, mww-aws commented on src/arg_satcomp_solver_base/satcomp_solver_driver.py
> +    def list_object_keys(self, problem_bucket: str):
Done

2022-05-27 18:13 UTC, eidelmanjonathan approved these changes

2022-05-27 18:26 UTC, merged